### ISSUE TITLE
Labels for Secrets

### ISSUE THREAD

**Issue by mbathe19** [Lerentis/bitwarden-crd-operator#60]
Hi,

I was wondering if there is a way to add labels to the secret? Some applications need them f.e. argocd.

Example:
```
spec:
  content:
    - element:
        secretName: 'username' # for example password
        secretRef: 'username'
        secretScope: 'login' # for custom entries on bitwarden use 'fields'
  name: 'name'
  namespace: 'namespace'
  labels:
    label: 'xyz'
```
Is it possible or is there another way?

Regards
